### ISSUE TITLE
[FEAT] COMPONENT > Navigation Menu (Dark)

### ISSUE THREAD

**Issue by oreoluwa212** [kinxlo/Language-learning-ai#2]
### Description
Develop the dark mode navbar displayed on all the pages.

### Purpose
It provides a component for showing the navbar.

### Requirement
- Ensure that the typography (text colors, font weights, font sizes, etc.) remains consistent with the design.
- Ensure that the card design (border colors, background color, text content, etc.) remains consistent with the design.
- Ensure the logo links to the application's home route.
- Ensure that the component is responsive on mobile devices by displaying the hamburger shown in the design and implementing the mobile navbar that shows when the hamburger is clicked.

### Expected Outcome
- A component that displays the navigation bar on all pages.

### Testing
- Make use of the react testing library to write unit tests for this component (Note that this library is already installed in the project codebase).
- Test different scenarios/cases to model a real-life use of the component

### Task
- [ ] Create a navbar component and use all expected reusable components(buttons)
- [ ] Make the navbar responsive for mobile devices.
- [ ] Write unit tests to ensure the component works as expected.

### Links
- [Figma - Link](https://www.figma.com/design/7Jl49r5rLPVzqorAVLKF1x/Team-Language-Learning-AI?node-id=1416-5507&t=CSRkR8M9i4SgBWLc-4)

### Images
![Device=Desktop, Type=WebPage-Dark, Signed=In](https://github.com/user-attachments/assets/0cded091-ff45-4f9f-8217-aa8b2844f0e0)

### Acceptance Criteria
- Create a navbar component that displays the app logo, navigation links, and every other thing according to the design
- This component should allow for mobile responsiveness.
- Write unit tests for this component to model expected behavior.
